#!/usr/bin/env bash
# docflow map — one compact, token-light index of the whole docs tree.
# Each line: relative/path — purpose (first H1). An agent reads this ONE file,
# knows the layout, and opens the exact doc it needs. No tree-scanning.
#
# Usage: docflow-map.sh [docs-root]   (default: docs)   → writes <root>/INDEX.md

set -euo pipefail
ROOT="${1:-docs}"
[ -d "$ROOT" ] || { echo "no docs root: $ROOT" >&2; exit 1; }
OUT="$ROOT/INDEX.md"

{
  echo "# Docs map — $(basename "$ROOT")/"
  echo "<!-- AUTO-GENERATED by docflow-map.sh. Lines = path — purpose. Open the exact doc. -->"
  echo
  # files grouped by top folder, alpha; one line each
  find "$ROOT" -type f -name '*.md' ! -name 'INDEX.md' | LC_ALL=C sort | while IFS= read -r f; do
    rel="${f#"$ROOT"/}"
    desc="$(grep -m1 -E '^#[^#]' "$f" 2>/dev/null | sed -E 's/^#+[[:space:]]*//; s/<!--.*-->//')"
    [ -z "$desc" ] && desc="—"
    printf '%s — %s\n' "$rel" "$desc"
  done
} > "$OUT"

echo "docflow: wrote $OUT ($(grep -c ' — ' "$OUT") entries)"
