#!/usr/bin/env bash
# docflow spec generator — read a code module, emit a PRE-FILLED spec draft.
# Not magic: heuristic discovery (grep). The agent/dev verifies + trims after.
# This is the "utility" — a spec that starts with real files/exports/APIs, not blanks.
#
# Usage: docflow-spec.sh <code-path> [--docs-root docs] [--target .] [--stdout]

set -euo pipefail

SRC=""; DOCS_ROOT="docs"; TARGET="$PWD"; TO_STDOUT=0
require_value() {
  opt="$1"
  value="${2-}"
  case "$value" in
    ''|--*)
      echo "missing value for $opt" >&2
      exit 1
      ;;
  esac
}
while [ $# -gt 0 ]; do
  case "$1" in
    --docs-root) require_value "$1" "${2-}"; DOCS_ROOT="$2"; shift 2 ;;
    --target)    require_value "$1" "${2-}"; TARGET="$2";    shift 2 ;;
    --stdout)    TO_STDOUT=1;    shift ;;
    -h|--help)   grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) SRC="$1"; shift ;;
  esac
done
if [ -z "$SRC" ] || [ ! -d "$SRC" ]; then
  echo "usage: docflow-spec.sh <code-path> [--docs-root docs]" >&2
  exit 1
fi

# repo-relative module path for the doc (strip target prefix)
REL="${SRC#"$TARGET"/}"; REL="${REL#./}"
NAME="$(basename "$SRC" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/-\{2,\}/-/g;s/^-//;s/-$//')"
MON="$(date +%b | tr '[:upper:]' '[:lower:]')-$(date +%y)"
EXT='\.(sh|ts|tsx|js|jsx|py|go|rb|java|rs|php|vue|svelte|cs|kt|swift)$'

# --- discovery helpers (top-N, unique, noise-trimmed) -------------------------
files()    { find "$SRC" -type f 2>/dev/null | grep -E "$EXT" | sed "s#^$SRC/##" | LC_ALL=C sort || true; }
exports()  { grep -rhoE 'export (default function|function|const|class|interface|type) [A-Za-z0-9_]+' "$SRC" 2>/dev/null \
             | awk '{print $NF}' | LC_ALL=C sort -u || true; }
types()    { grep -rhoE '(interface|type|enum) [A-Z][A-Za-z0-9_]+' "$SRC" 2>/dev/null | awk '{print $2}' | LC_ALL=C sort -u || true; }
apis()     { grep -rhoE "['\"]/[a-zA-Z0-9/_:.-]+['\"]" "$SRC" 2>/dev/null | tr -d "'\"" | LC_ALL=C sort -u | grep -vE '^/$' || true; }
hooks()    { grep -rhoE 'use[A-Z][A-Za-z0-9_]+' "$SRC" 2>/dev/null | LC_ALL=C sort -u || true; }
verbs()    { grep -rhoE '\.(get|post|put|patch|delete)\(' "$SRC" 2>/dev/null | tr -d '.(' | LC_ALL=C sort | uniq -c | sort -rn || true; }

bullets()  { local n="$1"; local s; s="$(cat)"; [ -z "$s" ] && { echo "- _none found_"; return; }; echo "$s" | head -"$n" | sed "s/^/- \`/;s/$/\`/"; }

NFILE=$(files | wc -l | tr -d ' ')

emit() {
cat <<EOF
<!-- docflow spec (auto-draft, $MON). Generated by docflow-spec.sh from $SRC — VERIFY + trim. -->
# ${NAME} — Technical Specification

**Module:** \`$REL\`
**Files:** $NFILE source files

## Architecture
<!-- auto-discovered exports — group these into the real component/service map -->
$(exports | bullets 20)

## Data
<!-- types / interfaces / enums found in module -->
$(types | bullets 20)

## API
<!-- string paths + HTTP verbs found — confirm which are real endpoints -->
$(apis | grep -E '^/' | head -15 | sed "s/^/- \`/;s/$/\`/" | sed "s/^- \`\`$//" || true)

HTTP verbs used:
$(verbs | head -8 | awk '{print "- "$2" ×"$1}')

## Flow
<!-- hooks / state entry points -->
$(hooks | bullets 20)

## Files
$(files | head -40 | sed "s/^/- \`/;s/$/\`/")
$(if [ "$NFILE" -gt 40 ]; then echo "- … +$((NFILE-40)) more"; fi)

## Risks
<!-- fill: edge cases, failure modes, coupling. Auto-gen can't infer these. -->

Related:
- Plan: [\`plans/features/($MON)-${NAME}.md\`](<../plans/features/($MON)-${NAME}.md>)
- Review: [\`reviews/active/($MON)-${NAME}.md\`](<../reviews/active/($MON)-${NAME}.md>)
EOF
}

if [ "$TO_STDOUT" = 1 ]; then emit; exit 0; fi

OUT="$TARGET/$DOCS_ROOT/specs/($MON)-${NAME}.md"
mkdir -p "$(dirname "$OUT")"
if [ -e "$OUT" ]; then echo "exists, not overwriting: $OUT (use --stdout to preview)" >&2; exit 0; fi
emit > "$OUT"
echo "docflow: wrote $OUT  (from $SRC — verify the draft)"
